# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import pytest
import yaml
from conftest import ROOT, fixture_table

from hiveroute.cli import main
from hiveroute.errors import RouteError
from hiveroute.gateway import budget_notes, litellm_config
from hiveroute.table import Table, load_table


def mixed_with_gateway() -> Table:
    t = fixture_table()
    data = yaml.safe_load(yaml.safe_dump(t.data))
    for pid, pool in data["pools"].items():
        if pool["kind"] == "metered":
            pool["gateway_key_env"] = pid.upper().replace("-", "_") + "_KEY"
    for route in data["routes"].values():
        route.setdefault("gateway_model", "provider/" + route["model"])
    return Table.from_data(data)


def test_metered_and_local_routes_only_by_default():
    t = mixed_with_gateway()
    cfg = litellm_config(t)
    names = {m["model_name"] for m in cfg["model_list"]}
    kinds = {t.pools[t.routes[n]["pool"]]["kind"] for n in names}
    assert "subscription" not in kinds and names
    m = cfg["model_list"][0]
    assert m["model_info"]["id"] == t.route_pin(m["model_name"])
    assert f"route:{m['model_name']}" in m["litellm_params"]["tags"]
    assert cfg["router_settings"]["num_retries"] == 0 and cfg["router_settings"]["fallbacks"] == []
    assert cfg["litellm_settings"]["drop_params"] is False
    assert cfg["general_settings"]["store_model_in_db"] is False
    assert any("per month" in n for n in budget_notes(t))


def test_missing_gateway_fields_are_errors():
    with pytest.raises(RouteError, match="no gateway_model"):
        litellm_config(fixture_table())


def test_ollama_route_derives_its_model(capsys):
    t = load_table(ROOT / "examples" / "1-hive.yaml")
    [m] = litellm_config(t)["model_list"]
    assert m["model_name"] == "qwen-local"
    assert m["litellm_params"]["model"] == "ollama_chat/qwen3:8b"
    assert m["litellm_params"]["api_base"] == "http://127.0.0.1:11434"
    assert main(["gateway-config", str(ROOT / "examples" / "1-hive.yaml")]) == 0
    out = capsys.readouterr().out
    assert out.startswith("# Generated by hive-route") and yaml.safe_load(out)["model_list"]

