# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import pytest
import yaml
from conftest import ROOT, fixture_table

from hiveroute.cli import main
from hiveroute.errors import RouteError
from hiveroute.gateway import budget_notes, litellm_config
from hiveroute.table import Table, load_table


def mixed_with_gateway() -> Table:
    t = fixture_table()
    data = yaml.safe_load(yaml.safe_dump(t.data))
    for pid, pool in data["pools"].items():
        if pool["kind"] == "metered":
            pool["gateway_key_env"] = pid.upper().replace("-", "_") + "_KEY"
    for route in data["routes"].values():
        route.setdefault("gateway_model", "provider/" + route["model"])
    return Table.from_data(data)


def test_metered_and_local_routes_only_by_default():
    t = mixed_with_gateway()
    cfg = litellm_config(t)
    names = {m["model_name"] for m in cfg["model_list"]}
    kinds = {t.pools[t.routes[n]["pool"]]["kind"] for n in names}
    assert "subscription" not in kinds and names
    m = cfg["model_list"][0]
    assert m["model_info"]["id"] == t.route_pin(m["model_name"])
    assert f"route:{m['model_name']}" in m["litellm_params"]["tags"]
    assert cfg["router_settings"]["num_retries"] == 0 and cfg["router_settings"]["fallbacks"] == []
    assert cfg["litellm_settings"]["drop_params"] is False
    assert cfg["general_settings"]["store_model_in_db"] is False
    assert any("per month" in n for n in budget_notes(t))


def test_missing_gateway_fields_are_errors():
    with pytest.raises(RouteError, match="no gateway_model"):
        litellm_config(fixture_table())


def test_ollama_route_derives_its_model(capsys):
    t = load_table(ROOT / "examples" / "1-hive.yaml")
    [m] = [m for m in litellm_config(t)["model_list"] if m["model_name"] == "qwen-local"]
    assert m["model_name"] == "qwen-local"
    assert m["litellm_params"]["model"] == "ollama_chat/qwen3:8b"
    assert m["litellm_params"]["api_base"] == "http://127.0.0.1:11434"
    assert main(["gateway-config", str(ROOT / "examples" / "1-hive.yaml")]) == 0
    out = capsys.readouterr().out
    assert out.startswith("# Generated by hive-route") and yaml.safe_load(out)["model_list"]



def test_budgets_for_metered_pools():
    from hiveroute.gateway import budgets
    b = budgets(mixed_with_gateway())
    assert b and all(x["name"].startswith("pool:") and x["budget_duration"] in ("1d", "1w", "1mo")
                     for x in b)


def test_each_period_gets_its_own_budget_tag():
    from hiveroute.gateway import budgets
    data = yaml.safe_load(yaml.safe_dump(mixed_with_gateway().data))
    pid = next(p for p, v in data["pools"].items() if v["kind"] == "metered")
    data["pools"][pid]["limits"] = [{"usd": 5, "per": "day"}, {"usd": 100, "per": "month"}]
    t = Table.from_data(data)
    names = [b["name"] for b in budgets(t)]
    assert f"pool:{pid}:day" in names and f"pool:{pid}:month" in names
    assert len(names) == len(set(names))
    m = next(m for m in litellm_config(t)["model_list"] if t.routes[m["model_name"]]["pool"] == pid)
    assert {f"pool:{pid}:day", f"pool:{pid}:month"} <= set(m["litellm_params"]["tags"])


def test_attempt_budget_only_for_metered_gateway_routes():
    from hiveroute.gateway import attempt_budget
    data = yaml.safe_load(yaml.safe_dump(mixed_with_gateway().data))
    pid = next(p for p, v in data["pools"].items() if v["kind"] == "metered")
    data["pools"][pid]["limits"] = [{"usd": 50, "per": "month"}, {"usd": 5, "per": "attempt"}]
    rid = next(r for r, v in data["routes"].items() if v["pool"] == pid)
    data["routes"][rid]["via_gateway"] = True
    t = Table.from_data(data)
    d = {"decision": "route", "via_gateway": True, "pool": pid, "attempt": "t.worker.0",
         "route_id": rid}
    assert attempt_budget(t, d) == {"name": "attempt:t.worker.0", "max_budget": 5,
                                    "budget_duration": "1mo",
                                    "description": f"hive-route: attempt t.worker.0 on {rid}"}
    assert attempt_budget(t, {**d, "via_gateway": False}) is None
    assert attempt_budget(t, {**d, "decision": "wait"}) is None
